### PR TITLE
re-work blowfish to 'detect' blowfish mode on decryption (identical to how fish10 works)

### LINKED ISSUE #127: Update processing of blowfish data
Fish10 uses an automated way to detect ECB vs CBC:
```
	if(l_cbc && !l_message.empty() && l_message[0] != '*')
	{
		// silent fallback to old style
		l_cbc = false;
	}
	else if(!l_cbc && !l_message.empty() && l_message[0] == '*')
	{
		// auto-enable new style even for non-prefixed keys
		l_cbc = true;
	}

	if(l_cbc && !l_message.empty() && l_message[0] == '*')
	{
		// strip asterisk
		l_message.erase(0, 1);
	}

	int l_decryptionResult = blowfish_decrypt_auto(l_cbc, l_message, l_newMsg, l_blowKey);
```

We need to implement this in DR too

### PR DESCRIPTION
**Pull request by mvangoor**
This should resolve #127

### CODE REVIEW

**Comment by k-2-r** [comment]
No sure to understand why we need this.
When talking to the bot in private, it's better to use DH1080 key exchange
When talking in public:
* If your bot is configured in CBC, talking to him in ECB is a security issue.
* If your bot is in ECB, talking to him in CBC will possibly not be correctly decrypted by the other people in the channel.
So whats the use case?

**Comment by zc0nf** [comment]
> No sure to understand why we need this.
> When talking to the bot in private, it's better to use DH1080 key exchange
> When talking in public:
> 
> * If your bot is configured in CBC, talking to him in ECB is a security issue.
> * If your bot is in ECB, talking to him in CBC will possibly not be correctly decrypted by the other people in the channel.
>   So whats the use case?

I agree

**Comment by mvangoor** [comment]
> 
> 
> No sure to understand why we need this.
> When talking to the bot in private, it's better to use DH1080 key exchange
> When talking in public:
> 
>     * If your bot is configured in CBC, talking to him in ECB is a security issue.
> 
>     * If your bot is in ECB, talking to him in CBC will possibly not be correctly decrypted by the other people in the channel.
>       So whats the use case?

Hey k2r, I did not think about if the bot is in CBC mode it would break security to also allow ECB. However if the bot is running in ECB mode it would make sense to also support CBC to allow for slow migrations?

I would then check the configured mode and if ECB then allow CBC decryption. If CBC ignore ECB...

What do you think?

**Comment by mvangoor** [comment]
So this is unwanted for channel communication. Let me do a final check how direct messages work.

**Pull request closed without merging**
